### PR TITLE
Signal

### PR DESCRIPTION
**Pull request by calebcabob**

### CODE REVIEW

**Comment by calebcabob** [comment]
Update angler signal and fingerprint

**Comment by IronSharpensIron2717** [comment]
You know there's source side and vendor stuff needed for assertive display right?

**Comment by calebcabob** [comment]
Yeah, Paul added the rest I thought

**Comment by IronSharpensIron2717** [comment]
Was never merged yet https://gerrit.bbqdroid.org/#/c/338/  and you need to use the muppers as vendor

**Pull request closed without merging**
